INSERT INTO category (description) VALUES ('American')
INSERT INTO category (description) VALUES ('Italian')
INSERT INTO category (description) VALUES ('Indian')
INSERT INTO category (description) VALUES ('Chinese')
INSERT INTO category (description) VALUES ('Mexican')
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon')
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon')
INSERT INTO unit_of_measure (description) VALUES ('cup')
INSERT INTO unit_of_measure (description) VALUES ('pinch')
INSERT INTO unit_of_measure (description) VALUES ('Dash')
INSERT INTO unit_of_measure (description) VALUES ('Each')
INSERT INTO unit_of_measure (description) VALUES ('Pint')
INSERT INTO unit_of_measure (description) VALUES ('Cup')

